# Generated by Django 2.1.7 on 2020-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_photo_url',
            field=models.ImageField(max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
